config/routes.rb
Rails.application.routes.draw do
  root 'top#new'
  resources :top
  get 'end' => 'top#end'
  # hackのルーティング
  get 'hackstep1' => 'hack#step1'
  get 'hackstep2' => 'hack#step2'
  get 'hackstep3' => 'hack#step3'
  get 'hackstep4' => 'hack#step4'
  get 'hackstep5' => 'hack#step5'
  get 'hackstep6' => 'hack#step6'
  get 'hackstep7' => 'hack#step7'
  get 'hackstep8' => 'hack#step8'
  get 'hackstep9' => 'hack#step9'
  get 'hackstep10' => 'hack#step10'
  get 'hackstep11' => 'hack#step11'
  get 'hackstep12' => 'hack#step12'
  get 'hackstep13' => 'hack#step13'
  get 'hackstep14' => 'hack#step14'
  # leakのルーティング
  get 'leakstep1' => 'leak#step1'
  get 'leakstep2' => 'leak#step2'
  get 'leakstep3' => 'leak#step3'
  get 'leakstep4' => 'leak#step4'
  get 'leakstep5' => 'leak#step5'
  get 'leakstep6' => 'leak#step6'
  get 'leakstep7' => 'leak#step7'
  get 'leakstep8' => 'leak#step8'
  get 'leakstep9' => 'leak#step9'
  get 'leakstep10' => 'leak#step10'
  get 'leakstep11' => 'leak#step11'
  get 'leakstep12' => 'leak#step12'
  get 'leakstep13' => 'leak#step13'
  get 'leakstep14' => 'leak#step14'
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  validates :number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hack_controller.rb
class HackController < ApplicationController
  def step9
    @user = get_user
  end

  def step10
    @user = get_user
  end

  def step11
    @user = get_user
  end

  def step12
    @user = get_user
  end

  private
  def get_user
    User.last
  end
end

app/controllers/leak_controller.rb
class LeakController < ApplicationController
  def step9
    @user = get_user
  end

  def step10
    @user = get_user
  end

  def step11
    @user = get_user
  end

  def step12
    @user = get_user
  end

  private
  def get_user
    User.last
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index

  end

  def new
    @user = User.new
  end

  def create
    User.create(create_params)
    redirect_to action: index
  end

  def end
  end

private
  def create_params
    params.require(:user).permit(:name, :number)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hack_helper.rb
module HackHelper
end

app/helpers/leak_helper.rb
module LeakHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/hack/step1.html.erb
<div id="process_desc" class="game">
  <ul id="process_li" class="background">
    <li class="process_li"><span class="red">マイナンバー</span>が流出！</li>
    <li class="dot_none">↓</li>
    <li class="process_li"><span class="red">個人情報</span>の流出…</li>
    <li class="dot_none">↓</li>
    <li class="process_li">口座を<span class="red">不正に開設</span></li>
    <li class="dot_none">↓</li>
    <li class="process_li">クレジットカードを不正に作成し、<span class="red">借金地獄</span>に…</li>
    <div class="buttons">
      <%= button_to 'この事件を体験する', '/hackstep2', method: :get, id: 'enter_game' %>
      <%= button_to '終わる', '/end', method: :get, id: 'end_game' %>
    </div>
  </ul>
</div>

app/views/hack/step10.html.erb
<div id="account_open" class="game">
  <div class="background">
    <p id="acount_open_com">
      これで<span class="red"><span id="hack_name2" class="hack_name"><%= @user.name %></span>さんの個人情報を取得</span>することが
      出来ました。この個人情報を使って<span class="red">不正に口座を開設する</span>ことができてしまいます…
    </p>
    <%= button_to '次へ', '/hackstep11', method: :get, id: 'next_hij_5' %>
  </div>
</div>

app/views/hack/step11.html.erb
<div id="opening_proc" class="game">
  <div id="opening_com">
    　お客様のデータ（右のデータ）を入力してください
  </div>
  <div id="opening_left">
    <form id="user_info_inp" onsubmit="judge(); return false;">
      <label for="user_name">名前</label>
      <input type="text" name="user_name" id="u_name" autocomplete="off">
      <label for="user_number">マイナンバー</label>
      <input type="text" name="user_number" id="u_number" autocomplete="off" maxlength="4">
      <label for="user_address">住所</label>
      <input type="text" name="user_address" id="user_address" autocomplete="off">
    </form>
    <button type="submit" name="submit" id="entry" value="登録" onclick="judge();　return false;">登録</button>
  </div>
  <div id="opening_right">
    <h4 class="data_title">名前</h4>
    <span id="hack_name3" class="hack_name"><%= @user.name %></span>
    <h4 class="data_title">マイナンバー</h4>
    <span id="mynumber2" class="mynumber"><%= @user.number %></span>
    <h4 class="data_title">住所</h4>
    <span class="address">大阪府大阪市天王寺区上本町六丁目八ー四</span>
  </div>
</div>

app/views/hack/step12.html.erb
<div id="acount_comp" class="game">
  <div class="background">
    <div class="user_aco_info">
      <h3 class="red">口座番号</h3>
      <span>xxxx-xxxx-xxx</span>
      <h3 class="red">名義人</h3>
      <span id="hack_name4" class="hack_name"><%= @user.name %></span><br>
      <%= button_to '次へ', '/hackstep13', method: :get, id: 'next_hij_6' %>
    </div>
  </div>
</div>

app/views/hack/step13.html.erb
<div id="create_card" class="game">
  <div class="background">
    <span id="create_card_com">作成しましょう！</span>
    <%= button_to 'カード作成', '/hackstep14', method: :get , id: 'create_card_btn' %>
  </div>
</div>

app/views/hack/step14.html.erb
<div id="use_card" class="game">
  <div class="background">
    <span id="counter">￥<span id="yen_counter">0</span></span>
    <button type="button" name="use_card" id="use_card_btn" onclick="usecard();">カード使用</button><br>
    <%= button_to '終わる', '/end', method: :get, id: 'finish' %>
    <div id="bills_stack">
    </div>
  </div>
</div>

app/views/hack/step2.html.erb
<div id="mynum_oflw" class="game">
  <div class="background">
    <div class="mynum_img"></div>
      <p id="mynum_oflw_com">
        あなたが<span class="red">先ほど入力した（擬似）マイナンバー</span>を覚えていますか？<br>
        あのような<span class="red">入力フォーム</span>に自分のマイナンバーを<wbr><span class="red">簡単に入力してしまうと</span><wbr>サイトの運営者やその関係者、<wbr>
        さらにはサイトに対して攻撃を仕掛ける人など、<wbr><span class="red">さまざまなところにあなたのマイナンバーを知られることになります。</span><br>
        マイナンバーを<span class="red">他人に知られることで、<wbr>さまざまな犯罪の被害者になる可能性</span>だけではなく、<wbr><span class="red">犯罪の加害者の一人になる可能性</span>も<wbr>
        はらんでいます。<br>
        今回は攻撃者の目線であなたのマイナンバーがどのように利用され、<wbr>先ほどの絵のような<span class="red">人生が狂ってしまう結果に至ったのか</span>を<wbr>見て行きましょう…<br>
      </p>
    <%= button_to '次へ', '/hackstep3', method: :get, id: 'next_hij_1' %>
  </div>
</div>

app/views/hack/step3.html.erb
<div id="mynum_use" class="game">
  <div class="background background_com">
    <p>
      まず、<span class="red">自治体のＰＣに不正にアクセス</span>をして、その中にあるデータベースからあなたが入力した（流出させてしまった）<span class="red">マイナンバーに
      ひも付いた個人情報を盗み出します</span>。
    </p>
    <ul>
      <li class="bg_com">自治体のＰＣは<span class="red">公式のサポートが終了した"Ｗｉｎｄｏｗｓ ＸＰ"を使用</span>し、"ＸＰの脆弱性"を利用して<span class="red">不正な方法でのアクセスが可能</span>な状態です。</li>
      <li class="bg_com">また、不運なことにそのＰＣで使用している<span class="red">データベース管理システムにも"ソフトウェア上の脆弱性"が存在</span>し、
                         簡単にデータベース内の内容にアクセスすることが可能な状態です。</li>
    </ul>
    <p>
      あなたの住む街の自治体のＰＣが不運にも上記のような状態であったため、あなたの流出したマイナンバーは<span class="red">攻撃者の格好の標的</span>となってしまったのです。
    </p>
    <%= button_to '次へ', '/hackstep4', method: :get, id: 'next_hij_2' %>
  </div>
</div>

app/views/hack/step4.html.erb
<div id="pc_access" class="game">
  <div class="background">
    <p class="access_com">
      自治体のデータベース管理システムの脆弱性を利用するために、<br>まず<span class="red">ＰＣに不正アクセス</span>をします。
    </p>
    <%= button_to 'アクセスする', 'hackstep5', method: :get, id: 'do_access' %>
    <div id="access_imgs">
      <div id="srv_img"></div>
      <div id="arr_img"></div>
      <div id="atc_img"></div>
    </div>
  </div>
</div>

app/views/hack/step5.html.erb
<div id="hack_acc">
  <div class="background">
    <h1 class="access_per">ＰＣに不正アクセス中…</h1>
    <div class="access_per">
      <div id="access_floatingBarsG">
        <div class="blockG" id="rotateG_01"></div>
        <div class="blockG" id="rotateG_02"></div>
        <div class="blockG" id="rotateG_03"></div>
        <div class="blockG" id="rotateG_04"></div>
        <div class="blockG" id="rotateG_05"></div>
        <div class="blockG" id="rotateG_06"></div>
        <div class="blockG" id="rotateG_07"></div>
        <div class="blockG" id="rotateG_08"></div>
      </div>
      <span id="access_per_num">0</span>%
    </div>
    <div id="access_line">
      <span class="expand"></span>
    </div>
    <span id="hack"></span>
  </div>
</div>

app/views/hack/step6.html.erb
<div id="hack_acc_comp">
  <div class="background hack_acc_comp">
    <h1>不正アクセスが完了しました</h1>
    <div id="excla_acc"></div>
    <%= button_to '次へ', '/hackstep7', method: :get, id: 'next_hij_3' %>
  </div>
</div>

app/views/hack/step7.html.erb
<div id="data_hack" class="game">
  <div class="background">
    <p class="data_hack_com">
      ＰＣにアクセスできたので<span class="red">データベースの情報を盗み</span>とりましょう。
    </p>
    <%= button_to 'ハックする', '/hackstep8', method: :get, id: 'do_data' %>
  </div>
</div>

app/views/hack/step8.html.erb
<div id="data_hacking">
      <div class="background">
        <h1 class="steal_per">ＰＣからデータを取得中…</h1>
        <div class="steal_per">
          <div id="steal_floatingBarsG">
            <div class="blockG" id="rotateG_01"></div>
            <div class="blockG" id="rotateG_02"></div>
            <div class="blockG" id="rotateG_03"></div>
            <div class="blockG" id="rotateG_04"></div>
            <div class="blockG" id="rotateG_05"></div>
            <div class="blockG" id="rotateG_06"></div>
            <div class="blockG" id="rotateG_07"></div>
            <div class="blockG" id="rotateG_08"></div>
          </div>
          <span id="steal_per_num">0</span>%
        </div>
        <div id="steal_line">
          <span class="expand"></span>
        </div>
        <span id="hack"></span>
      </div>
    </div>

app/views/hack/step9.html.erb
<div id="data_hack_comp">
  <div class="background hack_stl_comp">
    <h1>ハック完了しました</h1>
    <div id="excla_dat"></div>
    <p class="data_hack_com">
      <span id="hack_name1" class="red hack_name"><%= @user.name %></span>さんの<br>
      マイナンバーは<span id="mynumber1" class="red mynumber"><%= @user.number %></span>で、<br>
      住所は<span class="red">大阪府大阪市天王寺区六丁目八ー四</span>です。
    </p>
    <%= button_to '次へ', '/hackstep10', method: :get, id: 'next_hij_4' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mynumber</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/leak/step1.html.erb
<header id="game_head">
       <h2 class="sub_title">大きな原因は…？</h2>
</header>
<div id="process_desc" class="game">
  <ul id="process_li" class="background">
    <li class="process_li"><span class="red">マイナンバー</span>が流出！</li>
    <li class="dot_none">↓</li>
    <li class="process_li">ネット上に<span class="red">個人情報の書き込み</span>…</li>
    <li class="dot_none">↓</li>
    <li class="process_li">GoogleMap上で<span class="red">住所を調べられ、晒し者に</span>…！！</li>
    <div class="buttons">
      <%= button_to 'この事件を体験する', '/leakstep2', method: :get, id: 'enter_game' %>
      <%= button_to '終わる', '/end', method: :get, id: 'end_game' %>
    </div>
  </ul>
</div>

app/views/leak/step10.html.erb
<div id="do_leakage" class="game">
  <div class="background">
    <p class="leakage_com">
      これで<span class="red hack_name"><%= @user.name %></span>さんの個人情報を取得することが出来ました。<br>
      残るはこの情報を<span class="red">ネット上に書き込んで流出</span>させるだけです。
    </p>
    <%= button_to '次へ', '/leakstep11', method: :get, class: 'next_btn', id: 'next_lea_6' %>
  </div>
</div>

app/views/leak/step11.html.erb
<div id="opening_proc" class="game">
  <div id="leakage_inp_com">
     データを書き込んでください
  </div>
  <div id="opening_left_lea">
    <div id="leakage_inp_mes">５００：<span class="green">名無し：</span>2016/02/17(水) 16:03:49.31 ID:3r0e8GbC</div>
    <form id="user_info_inp" onsubmit="judge_lea(); return false;">
      <label for="user_name">名前：</label>
      <input type="text" name="user_name" id="u_name" autocomplete="off" autofocus="">
      <label for="user_number">マイナンバー：</label>
      <input type="text" name="user_number" id="u_number" autocomplete="off" maxlength="4">
      <label for="user_address">住所：</label>
      <input type="text" name="user_address" id="user_address" autocomplete="off">
      <label for="user_tel">電話番号：</label>
      <input type="text" name="user_tel" id="user_tel" autocomplete="off">
      <input type="submit" name="submit" id="entry" value="投稿" onsubmit="judge_lea(); return false;">
    </form>
  </div>
  <div id="opening_right_lea">
    <h4 class="data_title">名前</h4>
    <span id="hack_name3" class="hack_name"><%= @user.name %></span>
    <h4 class="data_title">マイナンバー</h4>
    <span id="mynumber2" class="mynumber"><%= @user.number %></span>
    <h4 class="data_title">住所</h4>
    <span class="address">大阪府大阪市天王寺区上本町六丁目八ー四</span>
    <h4 class="data_title">電話番号</h4>
    <span class="tel_num">080-0000-0000</span>
  </div>
</div>

app/views/leak/step12.html.erb
<div id="map_display">
  <div id="google_map"></div>
  <%= button_to '次へ', '/leakstep13', method: :get, class: 'next_btn', id: 'next_lea_7' %>
  <div id="comment_stack"></div>
  <script src="http://maps.google.com/maps/api/js?v=3&sensor=false" type="text/javascript" charset="UTF-8"></script>
  <script type="text/javascript">
  var user_name = <%= raw @user.name.to_json %>;
  var latlng = new google.maps.LatLng(34.663709, 135.518600);
      var opts = {
        zoom: 19,
        mapTypeId: google.maps.MapTypeId.ROADMAP,
        center: latlng
      };
  maps = new google.maps.Map(document.querySelector("#google_map"), opts);
  var infoWindowOpts = {
        position: new google.maps.LatLng(34.663805, 135.518600),
        content: user_name + "の住所はここですね？"
      };
  var infowin = new google.maps.InfoWindow(infoWindowOpts);
  infowin.open(maps);
  </script>
</div>

app/views/leak/step13.html.erb
<div id="do_leakage" class="game">
  <div class="background">
    <p class="leakage_com">
      もしも、<span class="red">マイナンバーが流出</span>してしまい、<span>個人情報が流出</span>してしまった場合、先ほどのように世界中の人に知られてしまい、最悪の場合、<span class="red">さまざまなイタズラや犯罪に巻き込まれる</span>事態が起きてしまうのです。
      <span class="center">マイナンバーの扱いには十分に注意しましょう！</span>
    </p>
  <%= button_to '終わる', '/end', method: :get, id: 'finish' %>
  </div>
</div>

app/views/leak/step2.html.erb
<div id="mynum_oflw" class="game">
  <div class="background">
    <div class="mynum_img"></div>
    <p id="mynum_oflw_com">
       あなたが<span class="red">先ほど入力した（擬似）マイナンバー</span>を覚えていますか？<br>
       あのような<span class="red">入力フォーム</span>に自分のマイナンバーを<wbr><span class="red">簡単に入力してしまうと</span><wbr>サイトの運営者やその関係者、<wbr>
       さらにはサイトに対して攻撃を仕掛ける人など、<wbr><span class="red">さまざまなところにあなたのマイナンバーを知られることになります。</span><br>
       マイナンバーを<span class="red">他人に知られることで、<wbr>さまざまな犯罪の被害者になる可能性</span>だけではなく、<wbr><span class="red">犯罪の加害者の一人になる可能性</span>も<wbr>
       はらんでいます。<br>
       今回は攻撃者の目線であなたのマイナンバーがどのように利用され、<wbr>先ほどの絵のような<span class="red">人生が狂ってしまう結果に至ったのか</span>を<wbr>見て行きましょう…<br>
     </p>
    <%= button_to '次へ', '/leakstep3', method: :get, class: 'next_btn', id: 'next_lea_1' %>
  </div>
</div>

app/views/leak/step3.html.erb
<div id="mynum_use" class="game">
  <div class="background background_com">
    <p>
     まず、<span class="red">自治体のＰＣに不正にアクセス</span>をして、その中にあるデータベースからあなたが入力した（流出させてしまった）<span class="red">マイナンバーにひも付いた個人情報を盗み出します</span>。
    </p>
    <ul>
      <li class="bg_com">自治体のＰＣは<span class="red">公式のサポートが終了した"Ｗｉｎｄｏｗｓ ＸＰ"を使用</span>し、"ＸＰの脆弱性"を利用して<span class="red">不正な方法でのアクセスが可能</span>な状態です。</li>
      <li class="bg_com">また、不運なことにそのＰＣで使用している<span class="red">データベース管理システムにも"ソフトウェア上の脆弱性"が存在</span>し、簡単にデータベース内の内容にアクセスすることが可能な状態です。</li>
    </ul>
    <p>
      あなたの住む街の自治体のＰＣが不運にも上記のような状態であったため、あなたの流出したマイナンバーは<span class="red">攻撃者の格好の標的</span>となってしまったのです。
    </p>
    <%= button_to '次へ', '/leakstep4', method: :get, class: 'next_btn', id: 'next_lea_2' %>
  </div>
</div>

app/views/leak/step4.html.erb
<div id="pc_access" class="game">
  <div class="background">
    <p class="access_com">
      自治体のデータベース管理システムの脆弱性を利用するために、<br>まず<span class="red">ＰＣに不正アクセス</span>をします。
    </p>
    <%= button_to 'アクセスする', 'leakstep5', method: :get, id: 'do_access' %>
    <div id="access_imgs">
      <div id="srv_img"></div>
      <div id="arr_img"></div>
      <div id="atc_img"></div>
    </div>
  </div>
</div>

app/views/leak/step5.html.erb
<div id="hack_acc">
  <div class="background">
    <h1 class="access_per">ＰＣに不正アクセス中…</h1>
    <div class="access_per">
      <div id="access_floatingBarsG">
        <div class="blockG" id="rotateG_01"></div>
        <div class="blockG" id="rotateG_02"></div>
        <div class="blockG" id="rotateG_03"></div>
        <div class="blockG" id="rotateG_04"></div>
        <div class="blockG" id="rotateG_05"></div>
        <div class="blockG" id="rotateG_06"></div>
        <div class="blockG" id="rotateG_07"></div>
        <div class="blockG" id="rotateG_08"></div>
      </div>
      <span id="access_per_num">0</span>%
    </div>
    <div id="access_line">
      <span class="expand"></span>
    </div>
    <span id="leak"></span>
  </div>
</div>

app/views/leak/step6.html.erb
<div id="hack_acc_comp">
  <div class="background hack_acc_comp">
    <h1>不正アクセスが完了しました</h1>
    <div id="excla_acc"></div>
    <%= button_to '次へ', '/leakstep7', method: :get, class: 'next_btn', id: 'next_lea_3' %>
  </div>
</div>

app/views/leak/step7.html.erb
<div id="data_hack" class="game">
  <div class="background">
    <p class="data_hack_com">
      ＰＣにアクセスできたので<span class="red">データベースの情報を盗み</span>とりましょう。
    </p>
    <%= button_to 'ハックする', '/leakstep8', method: :get, id: 'do_data' %>
  </div>
</div>

app/views/leak/step8.html.erb
<div id="data_hacking">
  <div class="background">
    <h1 class="steal_per">ＰＣからデータを取得中…</h1>
    <div class="steal_per">
      <div id="steal_floatingBarsG">
        <div class="blockG" id="rotateG_01"></div>
        <div class="blockG" id="rotateG_02"></div>
        <div class="blockG" id="rotateG_03"></div>
        <div class="blockG" id="rotateG_04"></div>
        <div class="blockG" id="rotateG_05"></div>
        <div class="blockG" id="rotateG_06"></div>
        <div class="blockG" id="rotateG_07"></div>
        <div class="blockG" id="rotateG_08"></div>
      </div>
      <span id="steal_per_num">0</span>%
    </div>
    <div id="steal_line">
      <span class="expand"></span>
    </div>
    <span id="leak"></span>
  </div>
</div>

app/views/leak/step9.html.erb
<div id="data_hack_comp">
  <div class="background hack_stl_comp">
    <h1>ハック完了しました</h1>
    <div id="excla_dat"></div>
    <p class="data_hack_com">
      <span id="hack_name1" class="red hack_name"><%= @user.name %></span>さんの<br>
      マイナンバーは<span id="mynumber1" class="red mynumber"><%= @user.number %></span>で、<br>
      住所は<span class="red">大阪府大阪市天王寺区六丁目八ー四</span>です。
      電話番号は<span class="red">080-0000-0000</span>です。
    </p>
    <%= button_to '次へ', '/leakstep10', method: :get, class: 'next_btn', id: 'next_lea_5' %>
  </div>
</div>

app/views/top/end.html.erb
<div class="background">
  <h1 id="last_message">また遊んでね！</h1>
  <%= button_to '戻る', '/', method: :get, id: 'return_btn' %>
</div>

app/views/top/index.html.erb
<h2 id="omikuji_title">マイナンバー占い</h2>

<!-- <div class="background"> -->
  <div id="maku"></div>
  <button type="button" name="omikuji_do" id="omikuji_do" onclick="omikuji();">占う</button>
  <!-- <div id="leakstep_ver"> -->
    <div class="result">
      <span class="big">大凶</span><br>
      <p>
        <span class="red">口座を乗っ取られて</span>しまいました…！！
        <!-- <br>十分に注意しましょう。 -->
        <div id="leak_result" class="result_image"></div>
        <%= link_to '次へ', 'hackstep1',id:"to_hackstep" %>
      </p>
    </div>
  </div>
  <div id="hackstep_ver">
    <div class="result">
      <span class="big">大凶</span><br>
      <p>
        <span class="red">住所が流失して</span>しまいました…！！
        <!-- <br>十分に注意しましょう。 -->
        <div id="hack_result" class="result_image"></div>
      </p>
      <%= link_to '次へ', 'leakstep1',id:"to_leakstep" %>
    <!-- </div> -->
  </div>
<!-- </div> -->

app/views/top/new.html.erb
<div class="omikuji_do">
<div class='login_form'>
  <!-- <h2>新規登録</h2> -->
  <h2 id="omikuji_title">マイナンバーってなんなんだー？</h2>
    <%= form_for @user, url: top_index_path do |f| %>
      <%= f.label :ニックネーム %>
      <%= f.text_field :name, id: 'login_form_name', autocomplete:"off" %><br>
      <%= f.label :マイナンバー（4桁） %>
      <%= f.text_field :number, maxlength: 4, id: 'login_form_number', autocomplete:"off" %><br>
      <!-- <%= f.submit '作成', class: 'login_form_submit' %> -->
      <button type="button" class="omikuji_do"name="omikuji_do" id="omikuji_do" onclick="omikuji();">占う</button>
    <% end %>
  </div>
</div>


   <!-- <div class="background"> -->
    <div id="maku"></div>
    <!-- <button type="button" name="omikuji_do" id="omikuji_do" onclick="omikuji();">占う</button> -->
    <div id="leakstep_ver">
      <div class="result">
        <span class="big">大凶</span><br>
        <p>
          <span class="red">口座を乗っ取られて</span>しまいました…！！
          <!-- <br>十分に注意しましょう。-->
          <div id="leak_result" class="result_image"></div>
          <%= link_to '次へ', 'hackstep1',id:"to_hackstep" %>
        </p>
      </div>
    </div>
    <div id="hackstep_ver">
      <div class="result">
        <span class="big">大凶</span><br>
        <p>
          <span class="red">住所が流失して</span>しまいました…！！
          <!-- <br>十分に注意しましょう。-->
          <div id="hack_result" class="result_image"></div>
        </p>
        <%= link_to '次へ', 'leakstep1',id:"to_leakstep" %>
      </div>
    <!-- </div> -->
  </div>

</div>